CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(256) NOT NULL,
    "ISBN" character varying(32) NOT NULL,
    "PublicationYear" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);


CREATE TABLE "Members" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(128) NOT NULL,
    "LastName" character varying(128) NOT NULL,
    "Email" character varying(256) NOT NULL,
    CONSTRAINT "PK_Members" PRIMARY KEY ("Id")
);


CREATE TABLE "Loans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId" integer NOT NULL,
    "MemberId" integer NOT NULL,
    "LoanDate" timestamp with time zone NOT NULL,
    "ReturnDate" timestamp with time zone,
    CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Loans_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Loans_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE RESTRICT
);


CREATE UNIQUE INDEX "IX_Books_ISBN" ON "Books" ("ISBN");


CREATE INDEX "IX_Loans_BookId" ON "Loans" ("BookId");


CREATE INDEX "IX_Loans_MemberId" ON "Loans" ("MemberId");


CREATE UNIQUE INDEX "IX_Members_Email" ON "Members" ("Email");


