-- Requirement 1: Books need authors
-- legacy changes:
-- Existing books remain valid for the response model even if they currently have zero authors.
-- GET /api/books returns an empty authors array for the legacy db rows that have no authors yet.
-- New author associations with books are stored in BookAuthors.

BEGIN;

CREATE TABLE "Authors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(128) NOT NULL,
    "LastName" character varying(128) NOT NULL,
    "Biography" character varying(4000),
    CONSTRAINT "PK_Authors" PRIMARY KEY ("Id")
);

CREATE TABLE "BookAuthors" (
    "BookId" integer NOT NULL,
    "AuthorId" integer NOT NULL,
    CONSTRAINT "PK_BookAuthors" PRIMARY KEY ("BookId", "AuthorId"),
    CONSTRAINT "FK_BookAuthors_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BookAuthors_Authors_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Authors" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_BookAuthors_AuthorId" ON "BookAuthors" ("AuthorId");

COMMIT;
